# command_manager.py
import json
from typing import List, Dict, Any

from supabase_client import supabase

TABLE_NAME = "commands"  # Supabase 側に用意するテーブル名


# -------------------------------------
# コマンド登録
# -------------------------------------
def register_command(**kwargs) -> Dict[str, Any]:
    """受け取ったフィールドで Supabase にコマンド登録する。"""
    try:
        data = supabase.table(TABLE_NAME).insert(kwargs).execute()
        return {"status": "success", "data": data.data}
    except Exception as e:
        return {"status": "error", "message": str(e)}


# -------------------------------------
# コマンド更新
# -------------------------------------
def update_command(command_id: int, cmd_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    cmd_data を JSON に変換して content に上書き
    """
    try:
        content_json = json.dumps(cmd_data)
        data = supabase.table(TABLE_NAME).update({
            "content": content_json,
            "action_type": "json"
        }).eq("id", command_id).execute()

        return {"status": "success", "data": data.data}
    except Exception as e:
        return {"status": "error", "message": str(e)}


# -------------------------------------
# コマンド削除
# -------------------------------------
def delete_command(command_id: int) -> Dict[str, Any]:
    try:
        data = supabase.table(TABLE_NAME).delete().eq("id", command_id).execute()
        return {"status": "success", "data": data.data}
    except Exception as e:
        return {"status": "error", "message": str(e)}


# -------------------------------------
# 全コマンド取得
# -------------------------------------
def get_all_commands() -> List[Dict[str, Any]]:
    try:
        response = supabase.table(TABLE_NAME).select("*").order("id").execute()
        rows = response.data or []

        commands = []
        for r in rows:
            content_json = {}
            try:
                if r.get("action_type") == "json" and r.get("content"):
                    content_json = json.loads(r["content"])
            except Exception as e:
                print(f"JSON parse error: {e}")

            commands.append({
                "id": r.get("id"),
                "name": r.get("name"),
                "action_type": r.get("action_type"),
                "content": r.get("content"),
                "triggers": content_json.get("triggers", []),
                "conditions": content_json.get("conditions", []),
                "actions": content_json.get("actions", []),
                "loop_count": content_json.get("loop_count", "once"),
                "linked_data": content_json.get("linked_data", {}),
                "trigger_type": r.get("trigger_type"),
                "trigger_value": r.get("trigger_value"),
                "calendar_event": r.get("calendar_event"),
                "memo_text": r.get("memo_text"),
                "tag": r.get("tag"),
            })
        return commands

    except Exception as e:
        print(f"Error fetching commands: {e}")
        return []


# -------------------------------------
# Supabase テーブル初期化 (任意)
# -------------------------------------
def init_table():
    """
    Supabase 側のテーブルはSQLエディタで次のクエリを実行して作ってください：
    CREATE TABLE IF NOT EXISTS commands (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text,
        action_type text,
        content text,
        trigger_type text,
        trigger_value text,
        repeat_interval text,
        condition_expr text,
        break_expr text,
        loop_count text,
        calendar_event text,
        memo_text text,
        tag text
    );
    """
    print("Supabase上で 'commands' テーブルを作成してください。")


# -------------------------------------
# テスト実行
# -------------------------------------
if __name__ == "__main__":
    print(get_all_commands())
